#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := app-template
include $(IDF_PATH)/make/project.mk

#COMPONENT_SRCDIRS=MQTTClient-C/src MQTTPacket/src MQTTClient-C/src/linux main
#COMPONENT_ADD_INCLUDEDIRS=MQTTClient-C/src MQTTPacket/src  MQTTClient-C/src/linux